export interface BootStep {
  message: string;
  delay: number; // ms after previous step
  type: 'info' | 'success' | 'warning' | 'error';
}

export const BIOS_STEPS: BootStep[] = [
  { message: '+====================================================+', delay: 300, type: 'info' },
  { message: '|                                                    |', delay: 200, type: 'info' },
  { message: '|                  NABIL SYSTEMS                      |', delay: 400, type: 'info' },
  { message: '|               CRAY X-MP/48 -- CLASS VI             |', delay: 400, type: 'info' },
  { message: '|           4 CPUs · 128 MW · NOS 2.0 rev 732        |', delay: 400, type: 'info' },
  { message: '|                                                    |', delay: 200, type: 'info' },
  { message: '+====================================================+', delay: 400, type: 'info' },
  { message: '', delay: 400, type: 'info' },
  { message: 'ROM BIOS v2.4.7 — Copyright 1987-2026 Nabil Microsystems Inc.', delay: 500, type: 'info' },
  { message: 'All rights reserved. Unauthorized duplication is a violation of applicable laws.', delay: 600, type: 'info' },
  { message: '', delay: 300, type: 'info' },
  { message: 'CPU: MOS 6502 @ 8MHz — coprocessor: Ann-9000 neural slice', delay: 700, type: 'success' },
  { message: 'MEM: 4.0 MB OK (640K conventional + 3.36M extended)', delay: 900, type: 'success' },
  { message: 'FDC: Reading cylinder 0, head 0, sector 1... OK', delay: 600, type: 'success' },
  { message: 'HDD: Seagate ST-238R — 128MB — CHS: 615/4/17 — LBA enabled', delay: 700, type: 'success' },
  { message: 'INT: Vector table loaded at 0x0000 — 256 entries', delay: 500, type: 'success' },
  { message: 'DMA: Controller 8237 — channels 0-3 active', delay: 400, type: 'success' },
  { message: 'PIT: 8253 timer — 18.2 Hz tick calibrated', delay: 400, type: 'success' },
  { message: 'CRT: Motorola 6845 — 80x25 text mode — phosphor P1', delay: 500, type: 'success' },
  { message: 'KBD: PC/AT controller — 8042 — scan code set 2 — num lock on', delay: 400, type: 'success' },
  { message: 'SER: COM1 at 0x3F8 — 9600 baud — no parity — 1 stop bit', delay: 450, type: 'success' },
  { message: 'SYS: RTC reports 2026-07-09T20:25 — battery OK', delay: 400, type: 'success' },
  { message: '', delay: 250, type: 'info' },
  { message: 'ROM EXT: Scanning for option ROMs at C000...', delay: 500, type: 'info' },
  { message: 'ROM EXT: C800 — NABIL/86 BIOS extension v2.4 found', delay: 500, type: 'success' },
  { message: 'ROM EXT: D000 — Bangla font ROM (24x24 glyph table)', delay: 600, type: 'success' },
  { message: 'ROM EXT: D800 — Network boot agent (PXE/NFTP)', delay: 400, type: 'success' },
  { message: '', delay: 200, type: 'info' },
  { message: 'ROM CHK: Boot block CRC16 0xA55A — match', delay: 350, type: 'success' },
  { message: 'ROM CHK: System region CRC16 0x3CC3 — match', delay: 350, type: 'success' },
  { message: '', delay: 150, type: 'info' },
  { message: '  Booting NABIL/86 v2.4 from HDD in 3... 2... 1...', delay: 1200, type: 'info' },
  { message: '<BLINK>_</BLINK>', delay: 300, type: 'info' },
];

export const BOOT_STEPS: BootStep[] = [
  { message: 'NABIL/86 Kernel init — stage 1 (real mode)', delay: 500, type: 'info' },
  { message: 'KRN: Switching to protected mode... GDT loaded at 0x000800', delay: 700, type: 'info' },
  { message: 'KRN: Protected mode engaged — paging enabled', delay: 500, type: 'success' },
  { message: 'KRN: Process scheduler — priority preemptive — quantum 30ms', delay: 450, type: 'success' },
  { message: 'KRN: Virtual memory manager — 16K pages — 64-entry TLB', delay: 450, type: 'success' },
  { message: 'KRN: VFS layer registered — ext2, tmpfs, procfs', delay: 400, type: 'success' },
  { message: 'KRN: ELF binary loader ready — 4G address space', delay: 400, type: 'success' },
  { message: 'KRN: Signal handler table — 32 standard signals', delay: 350, type: 'success' },
  { message: '', delay: 200, type: 'info' },
  { message: '  INIT: Spawning /sbin/init (PID 1)...', delay: 500, type: 'info' },
  { message: 'INIT: Mounting root filesystem — ext2, ro, errors=panic', delay: 500, type: 'success' },
  { message: 'INIT: Running /etc/rc.sysinit...', delay: 400, type: 'info' },
  { message: 'INIT: Loading kernel modules — bangla-font, nabil-console', delay: 500, type: 'success' },
  { message: 'INIT: Setting hostname — port.nabil.local', delay: 300, type: 'success' },
  { message: 'INIT: Configuring loopback — 127.0.0.1 — ok', delay: 300, type: 'success' },
  { message: '', delay: 200, type: 'info' },
  { message: 'FS: Checking /home/guest filesystem...', delay: 400, type: 'info' },
  { message: 'FS: Scanning user profile — ann', delay: 500, type: 'info' },
  { message: 'FS: Loading skills database (42 entries)', delay: 600, type: 'success' },
  { message: 'FS: Loading contact registry', delay: 350, type: 'success' },
  { message: 'FS: Verifying project manifests...', delay: 450, type: 'info' },
  { message: 'FS: Loading research corpus...', delay: 500, type: 'info' },
  { message: 'FS: Log journal — replaying 3 unread entries', delay: 400, type: 'warning' },
  { message: '', delay: 200, type: 'info' },
  { message: 'PROJ: AutoMLBench — sourcing benchmark suite... done', delay: 500, type: 'success' },
  { message: 'PROJ: TidyFlow — pipelining 12 stages — all green', delay: 450, type: 'success' },
  { message: 'PROJ: FireViz — rendering engine compiled on-the-fly', delay: 400, type: 'success' },
  { message: 'PROJ: NLP News Recommender — 14K doc corpus loaded to RAM', delay: 500, type: 'success' },
  { message: 'PROJ: Disease Predictor — model accuracy 94.2% — LOADED', delay: 500, type: 'success' },
  { message: 'PROJ: Movie Recommender — matrix factorization weights ready', delay: 400, type: 'success' },
  { message: '', delay: 200, type: 'info' },
  { message: '  quantum singularity detected in /projects — ignoring (harmless)', delay: 800, type: 'warning' },
  { message: '', delay: 150, type: 'info' },
  { message: 'PAPER: BENI Global 10 — arXiv:2606.10225 — 17 pages — indexed', delay: 700, type: 'success' },
  { message: 'PAPER: BENI v1.0 — HuggingFace — 4.2K narrative samples — loaded', delay: 700, type: 'success' },
  { message: 'PAPER: Institutional Quality & Finance — undergrad thesis — cited 12', delay: 600, type: 'success' },
  { message: '', delay: 200, type: 'info' },
  { message: 'NET: Bringing up interface lo... 127.0.0.1/8 — up', delay: 350, type: 'success' },
  { message: 'NET: Bringing up interface eth0... DHCPDISCOVER on port 67', delay: 500, type: 'info' },
  { message: 'NET: DHCPOFFER from 192.168.1.1 — lease 86400s', delay: 500, type: 'info' },
  { message: 'NET: eth0 — 192.168.1.42/24 gw 192.168.1.1 DNS 8.8.8.8', delay: 500, type: 'success' },
  { message: 'NET: /etc/resolv.conf — nameserver 8.8.8.8, 1.1.1.1', delay: 400, type: 'success' },
  { message: '', delay: 200, type: 'info' },
  { message: 'SRV: Terminal multiplexer — dtach — listening on pts/0-3', delay: 400, type: 'success' },
  { message: 'SRV: Window compositor — NABIL/WM v0.9 — 16-bit color', delay: 500, type: 'success' },
  { message: 'SRV: HTTP daemon — nabil-httpd/1.0 — port 80', delay: 400, type: 'success' },
  { message: 'SRV: WebSocket relay — wsd/0.2 — port 8080', delay: 400, type: 'success' },
  { message: 'SRV: Cron daemon — 3 scheduled jobs (daily log rot, backup, BENI fetch)', delay: 500, type: 'success' },
  { message: '', delay: 300, type: 'info' },
  { message: '>>> WARNING: /dev/random: entropy pool low — feeding from /dev/urandom', delay: 800, type: 'warning' },
  { message: '>>> WARNING: Coffee cup detected near drive bay — spill risk elevated', delay: 1000, type: 'warning' },
  { message: '>>> INFO:  We know what you did last summer. We approved.', delay: 900, type: 'info' },
  { message: '', delay: 300, type: 'info' },
  { message: '  =============================================', delay: 250, type: 'success' },
  { message: '    NABIL/86 v2.4 — Bangla NLP Edition', delay: 400, type: 'success' },
  { message: '    Uptime: 0.00s  |  User: ann  |  Load: 0.01', delay: 350, type: 'success' },
  { message: '    "চিন্তা করো, তারপর代码 করো।"', delay: 500, type: 'success' },
  { message: '  =============================================', delay: 250, type: 'success' },
  { message: '', delay: 400, type: 'info' },
  { message: 'System ready. Welcome back, Ann.', delay: 800, type: 'success' },
];
